const data = [
  {
    id: 1,
    name: "Survey Form Netflix",
    desc: "Made a survey form for Netflix. This is a code along project. Some responsiveness added.",
    category:"html-css",    
    liveSite: "https://cemispirli.github.io/Survey-Form-Netflix/",
    gif:"https://raw.githubusercontent.com/cemispirli/Survey-Form-Netflix/master/Survey%20Form%20Netflix.gif",
    github: "https://github.com/cemispirli/Survey-Form-Netflix",
  },  
  {
    id: 2,
    name: "Parallax Website",
    desc: "Basic parallax website to understand how it's made. This is a code along project.",
    category:"html-css",    
    liveSite: "https://cemispirli.github.io/Parallax-Website/",
    gif:"https://raw.githubusercontent.com/cemispirli/Parallax-Website/master/paralax.gif",
    github: "https://github.com/cemispirli/Parallax-Website",
  },
  {
    id: 3,
    name: "Google Landing Page",
    desc: "Made google landing page clone using HTML & CSS. Page is not using JS. This project is made to reinforce HTML & CSS knowledge.",
    category:"html-css",
    liveSite: "https://cemispirli.github.io/Google-Landing-Page/",
    gif:"https://raw.githubusercontent.com/cemispirli/Google-Landing-Page/master/Google%20Landing%20Page.gif",
    github: "https://github.com/cemispirli/Google-Landing-Page",
  },
  {
    id: 4,
    name: "Sass Portfolio Project",
    desc: "Made a four page application using HTML, CSS and SCSS. Some degree of responsiveness is added.",
    category:"html-css",
    liveSite: "https://cemispirli.github.io/Sass-Project/",
    gif:"https://raw.githubusercontent.com/cemispirli/Sass-Project/master/Saas%20Project.gif",
    github: "https://github.com/cemispirli/Sass-Project",
  },
  {
    id: 5,
    name: "Checkout Form",
    desc: "This is a checkout form made using HTML & CSS. This is a code along project. Some degree of responsiveness is added.",
    category:"html-css",
    liveSite: "https://cemispirli.github.io/Checkout-Form/",
    gif:"https://raw.githubusercontent.com/cemispirli/Checkout-Form/master/Checkout-Form.gif",
    github: "https://github.com/cemispirli/Checkout-Form",
  },
  {
    id: 6,
    name: "Team Members Page",
    desc: "Made a team members page using HTML, CSS and JS. This is a code along project. Some degree of responsiveness is added.",
    category:"html-css",
    liveSite: "https://cemispirli.github.io/Team-Members-Page/",
    gif:"https://raw.githubusercontent.com/cemispirli/Team-Members-Page/master/Team%20Members%20Page.gif",
    github: "https://github.com/cemispirli/Team-Members-Page",
  },
  {
    id: 7,
    name: "Bootstrap School Project",
    desc: "Made a four page application using HTML, CSS and Bootstrap. This is a code along project. Some degree of responsiveness is added.",
    category:"html-css",
    liveSite: "https://cemispirli.github.io/Bootstrap-Clarusway-School-Project/",
    gif:"https://raw.githubusercontent.com/cemispirli/Bootstrap-Clarusway-School-Project/master/Bootstrap%20Clarusway%20School%20Project.gif",
    github: "https://github.com/cemispirli/Bootstrap-Clarusway-School-Project",
  },
  {
    id: 8,
    name: "Exact Age Calculator",
    desc: "Made a exact age calculator using HTML, CSS and JS. This is a code along project. Some degree of responsiveness is added.",
    category:"javascript",
    liveSite: "https://cemispirli.github.io/Exact-Age-Calculator/",
    gif:"https://raw.githubusercontent.com/cemispirli/Exact-Age-Calculator/master/exactagecalculator.gif",
    github: "https://github.com/cemispirli/Exact-Age-Calculator",
  },
  {
    id: 9,
    name: "Lottery Game",
    desc: "Made a lottery game using HTML, CSS and JS. This is a code along project. Some degree of responsiveness is added.",
    category:"javascript",
    liveSite: "https://cemispirli.github.io/Lottery-Game/",
    gif:"https://raw.githubusercontent.com/cemispirli/Lottery-Game/master/lotterygame.gif",
    github: "https://github.com/cemispirli/Lottery-Game",
  },
  {
    id: 10,
    name: "Find The Number Game",
    desc: "Made a find the number game using HTML, CSS and JS. This is a code along project. Some degree of responsiveness is added.",
    category:"javascript",
    liveSite: "https://cemispirli.github.io/Find-The-Number-Game/",
    gif:"https://raw.githubusercontent.com/cemispirli/Find-The-Number-Game/master/findthenumber.gif",
    github: "https://github.com/cemispirli/Find-The-Number-Game",
  },
  {
    id: 11,
    name: "Todo List",
    desc: "Made a todo list using HTML, CSS and JS. This is a code along project. Some degree of responsiveness is added.",
    category:"javascript",
    liveSite: "https://cemispirli.github.io/ToDo-App/",
    gif:"https://raw.githubusercontent.com/cemispirli/ToDo-App/master/todoappjs.gif",
    github: "https://github.com/cemispirli/ToDo-App",
  },
  {
    id: 12,
    name: "Ios Calculator",
    desc: "Simple IOS calculator app. I struggled with JS a little but in the end variable swapping helped me solve the problems.",
    category:"javascript",
    liveSite: "https://cemispirli.github.io/IOS-Calculator/",
    gif:"https://raw.githubusercontent.com/cemispirli/IOS-Calculator/master/ios%20calculator.gif",
    github: "https://github.com/cemispirli/IOS-Calculator",
  },
  {
    id: 13,
    name: "Checkout Page",
    desc: "Checkout page made using HTML, CSS and JS. This is a code along project. Some degree of responsiveness is added.",
    category:"javascript",
    liveSite: "https://cemispirli.github.io/Checkout-Page/",
    gif:"https://raw.githubusercontent.com/cemispirli/Checkout-Page/master/checkoutpage.gif",
    github: "https://github.com/cemispirli/Checkout-Page",
  },
  {
    id: 14,
    name: "StopWatch",
    desc: "Simple stopwatch page with start, stop & reset buttons. No CSS pure HTML & JS.",
    category:"javascript",
    liveSite: "https://cemispirli.github.io/StopWatch/",
    gif:"https://raw.githubusercontent.com/cemispirli/StopWatch/master/stopwatch.gif",
    github: "https://github.com/cemispirli/StopWatch",
  },
  {
    id: 15,
    name: "Movie Seat Booking",
    desc: "Movie seat booking page with a little bit of CSS. This is a code along project. Some degree of responsiveness is added.",
    category:"javascript",
    liveSite: "https://cemispirli.github.io/Movie-Seat-App/",
    gif:"https://raw.githubusercontent.com/cemispirli/Movie-Seat-App/master/movie%20seat%20app.gif",
    github: "https://github.com/cemispirli/Movie-Seat-App",
  },
  {
    id: 16,
    name: "Country Info Project",
    desc: "Country information project with a little bit of CSS. This is a code along project. Some degree of responsiveness is added.",
    category:"javascript",
    liveSite: "https://cemispirli.github.io/Country-Information-Project/",
    gif:"https://raw.githubusercontent.com/cemispirli/Country-Information-Project/master/country%20information%20project.gif",
    github: "https://github.com/cemispirli/Country-Information-Project",
  },
  {
    id: 17,
    name: "Jquery Weather App",
    desc: "Project aims to display current weather data of searched city around the world with fetching Weather Api data.",
    category:"javascript",
    liveSite: "https://cemispirli.github.io/Jquery-Weather-App/",
    gif:"https://raw.githubusercontent.com/cemispirli/Jquery-Weather-App/master/Jquery%20Weather%20App.gif",
    github: "https://github.com/cemispirli/Jquery-Weather-App",
  },
  {
    id: 18,
    name: "BirthdayReminder",
    desc: "Made a birthday reminder application using CSS and React. This is a code along project. Some degree of responsiveness is added.",
    category:"react",
    liveSite: "https://cemispirli.github.io/birthdayreminder/",
    gif:"https://raw.githubusercontent.com/cemispirli/birthdayreminder/master/birthdayreminder.gif",
    github: "https://github.com/cemispirli/birthdayreminder",
  },
  {
    id: 19,
    name: "Tour Project",
    desc: "React project that pulls an array of data from a local data.js. Then prints this data on card components to render. Fully responsive.",
    category:"react",
    liveSite: "https://cemispirli.github.io/tour-project/",
    gif:"https://raw.githubusercontent.com/cemispirli/tour-project/master/tourproject.gif",
    github: "https://github.com/cemispirli/tour-project",
  },
  {
    id: 20,
    name: "Language Cards",
    desc: "Simple app made to practice states.",
    category:"react",
    liveSite: "https://cemispirli.github.io/language-cards/",
    gif:"https://raw.githubusercontent.com/cemispirli/language-cards/master/languagecard.gif",
    github: "https://github.com/cemispirli/language-cards",
  },
  {
    id: 21,
    name: "Task Tracker",
    desc: "Task tracker made using React.js. Stores your input in the localStorage. Uses multiple components that are nested and passes states between them. Styling made using styled components.",
    category:"react",
    liveSite: "https://cemispirli.github.io/task-tracker/",
    gif:"https://raw.githubusercontent.com/cemispirli/task-tracker/master/tasktracker.gif",
    github: "https://github.com/cemispirli/task-tracker",
  },{
    id: 22,
    name: "Website Page With Router",
    desc: "Made a website page with react router. This is a code along project. Some degree of responsiveness is added.",
    category:"react",
    liveSite: "https://website-page-with-router.netlify.app/",
    gif:"https://raw.githubusercontent.com/cemispirli/website-page-with-router/master/website-page-with-router.gif",
    github: "https://github.com/cemispirli/website-page-with-router",
  },
  {
    id: 23,
    name: "Recipe App",
    desc: "Multi page recipe app. You type a ingredient and a meal time and it returns you food suggestions that you can cook with that specific ingredient. When you click on the recipe you are interested in it takes you to a new page with detailed instructions and image of the food.",
    category:"react",
    liveSite: "https://recipe-app-github.netlify.app/",
    gif:"https://raw.githubusercontent.com/cemispirli/recipe-app/master/recipeapp.gif",
    github: "https://github.com/cemispirli/recipe-app",
  },
  {
    id: 24,
    name: "Firebase Movie App",
    desc: "A movie app search site. You can register via firebase auth. Login using the registered acc. or login via Google. If you login you can see the rates of each movie, use the search bar and click on movie pictures will take you to a details page with more details regarding the movies. I added react toastify to manage login/logout pop ups.",
    category: "react",
    liveSite: "https://firebase-movie-app.netlify.app/",
    gif:"https://raw.githubusercontent.com/cemispirli/firebase-movie-app/master/reactmovieapp.gif",
    github: "https://github.com/cemispirli/firebase-movie-app",
  },
  {
    id: 25,
    name: "Random User App",
    desc: "Made a project that use an open source REST API to fetch a random persons data and render on page on click to different buttons. User can use the add user button to add current user values to an array. We map this array to render table row elements with the data.",
    category: "react",
    liveSite: "https://random-user-app8.netlify.app/",
    gif:"https://raw.githubusercontent.com/cemispirli/Random-User-App-2/master/randomuserapp.gif",
    github: "https://github.com/cemispirli/Random-User-App-2",
  },
  {
    id: 26,
    name: "Firebase Contact App",
    desc: "A contact app that uses firebase to store data. You can add a contact, delete a contact, edit a contact. ",
    category: "react",
    liveSite: "https://firebase-contact-app08.netlify.app/",
    gif:"https://raw.githubusercontent.com/cemispirli/firebase-contact-app/2d1f84d762ffe4333a15456e43512c4de4d99b20/firabasecontactapp.gif",
    
    github: "https://github.com/cemispirli/firebase-contact-app",
  },
  {
    id: 27,
    name: "Django Blog App",
    desc: "A blog app that uses Django as backend. You can add a post, delete a post, edit a post. ",
    category: "django",
    liveSite: "https://jamespearly.pythonanywhere.com/",
    gif:"https://raw.githubusercontent.com/cemispirli/BlogApp/master/djangoblogapp.gif",
    github: "https://github.com/cemispirli/BlogApp",
  },
  {
    id: 28,
    name: "Turkey Weather App",
    desc: "Weather App that uses React turkey ,redux ,redux toolkit, React Router and Open Weather API. You can search for a city and it will return you the weather data of that city. ",
    category: "react",
    liveSite: "https://weather-turkey.netlify.app/",
    gif:"https://raw.githubusercontent.com/cemispirli/weather-turkey-map/master/Weather-turkey.gif",
    github: "https://github.com/cemispirli/weather-turkey-map",
  },
  {
    id: 29,
    name: "Blog App with Firebase",
    desc: "A blog app that uses firebase as server. You can add a post, delete a post, edit a post. ",
    category: "react",
    liveSite: "https://blog-app-with-firebase.netlify.app/",
    gif:"https://raw.githubusercontent.com/cemispirli/capstone-project/master/Capstone-project.gif",
    github: "https://github.com/cemispirli/capstone-project",
  },
  

];



export default data;
